#!/bin/sh

if [ "$CI" = true ]; then
  exit 0
fi

# source the root env for environment
if [ -f ".env" ]; then
  source .env
fi

if [ -z "$ENVIRONMENT" ]; then
  echo "ENVIRONMENT env variable must be set in root \`.env\` file"
  exit 1
fi

# load config
CONFIG=$(cat libs/environment/config.json)

# load infisical domain and project id
INFISICAL_DOMAIN=$(echo $CONFIG | jq -r '.infisicalDomain')
INFISICAL_PROJECT_ID=$(echo $CONFIG | jq -r '.infisicalProjectId')

# infisical for some reason only accepts 'dev' and 'prod' as env names
INFISICAL_ENVIRONMENT_MAP='{"development": "dev", "production": "prod"}'
INFISICAL_ENVIRONMENT=$(echo $INFISICAL_ENVIRONMENT_MAP | jq -r ".$ENVIRONMENT")

if [ ! -f "apps/jupiter/.env.local" ]; then
  echo "jupiter .env.local missing"
  exit 1
fi

source apps/jupiter/.env.local
if [ -z "$CONVEX_URL" ] || [ -z "$CONVEX_SITE_URL" ]; then
  echo "CONVEX_URL or CONVEX_SITE_URL missing"
  exit 1
fi

generate_env() {
  local TYPE="$1"
  local NAME="$2"
  local HAS_SECRETS="$3"
  local HAS_CONVEX="$4"

  local ENV_FILE="$TYPE/$NAME/.env.local"

  {
    echo "# ! IMPORTANT: This .env file is auto-generated by libs/environment."
    echo "# ! Do not edit this file directly."
    echo "ENVIRONMENT=$ENVIRONMENT"
  } > "$ENV_FILE"

  if [ "$HAS_SECRETS" = true ]; then
    echo "Loading secrets for project: $NAME"

    infisical secrets \
      --domain "$INFISICAL_DOMAIN" \
      --env "$INFISICAL_ENVIRONMENT" \
      --projectId "$INFISICAL_PROJECT_ID" \
      --path "/$NAME" \
      --output dotenv >> "$ENV_FILE"
  fi


  if [ "$HAS_CONVEX" = true ]; then
    if [ "$ENVIRONMENT" = "production" ]; then
      echo "Skipping convex environment variables for production environment"
    else
      echo "Loading convex env variables for project: $NAME"

      PUBLIC_PREFIX=$(
        echo "$CONFIG" |
        jq -r --arg dir "$TYPE" --arg name "$NAME" \
          '.[$dir][$name].publicPrefix // ""'
      )

      {
        echo ""
        echo "# convex variables"
        echo "${PUBLIC_PREFIX}CONVEX_URL=$CONVEX_URL"
        echo "${PUBLIC_PREFIX}CONVEX_SITE_URL=$CONVEX_SITE_URL"
      } >> "$ENV_FILE"
    fi
  fi
}

echo "$CONFIG" | jq -r '
  ["apps", "libs"][]
  as $type
  | .[$type]
  | to_entries[]
  | [
      $type,
      .key,
      (.value.hasSecrets // false),
      (.value.hasConvex // false)
    ]
  | @tsv
' |
while IFS=$'\t' read -r TYPE NAME HAS_SECRETS HAS_CONVEX; do
  generate_env \
    "$TYPE" \
    "$NAME" \
    "$HAS_SECRETS" \
    "$HAS_CONVEX"
done
